package tryCatchThrow;

public class StudentMain {
    public static void main(String[] args) throws StudentException {
        Student s1 = new Student();
        s1.find("12");
    }
}
